services:
  pastor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_WEB_PORT}:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:16
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
