services:
  pastor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_WEB_PORT}:8000"
    volumes:
      - "seqid:${APP_SEQID_PATH}"
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  seqid:
  postgres_data:
